version: 2

run: &abort_if_no_change
  name: Abort if no changes
  command: |
    git fetch origin develop:develop
    if [ $(git diff develop modules/$MODULE_NAME | wc -l) -gt 0 ] ; then
      circleci step halt
    fi

# Common step for adding Longtail PyPI index
default_test: &default_test
  docker:
    - image: circleci/python:3.6

  # CircleCI does not allow expansion of the path so we'll have to `cd`
  # into the correct submodule directory for each `run` step
  working_directory: ~/project

  steps:
    - checkout

    - run: *abort_if_no_change

    - restore_cache:
        keys:
          - v1-dependencies-{{ .Environment.MODULE_NAME }}-{{ checksum "requirements.txt" }}
          - v1-dependencies-{{ .Environment.MODULE_NAME }}
          - v1-dependencies-

    - run:
        name: Install Python Dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          cd modules/$MODULE_NAME
          pip install -r requirements.txt

    - save_cache:
        paths:
          - ./venv
        key: v1-dependencies-{{ .Environment.MODULE_NAME }}-{{ checksum "requirements.txt" }}

    - run:
        name: Lint module
        command: |
          . venv/bin/activate
          cd modules/$MODULE_NAME
          pylint pangea_modules/$MODULE_NAME

# CircleCI Jobs
jobs:
  test_base:
    <<: *default_test
    environment:
      MODULE_NAME: base

  test_humann2:
    <<: *default_test
    environment:
      MODULE_NAME: humann2

  test_krakenhll:
    <<: *default_test
    environment:
      MODULE_NAME: krakenhll

workflows:
  version: 2

  base_cd:
    jobs:
      - test_base
      - test_humann2
      - test_krakenhll
