version: 2

# Common step for adding Longtail PyPI index
default_lint: &default_lint
  docker:
    - image: circleci/python:3.6
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ .Environment.MODULE_NAME }}-{{ checksum "requirements.txt" }}
          - v1-dependencies-{{ .Environment.MODULE_NAME }}
          - v1-dependencies-
    - run:
        name: Install Python Dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          cd modules/$MODULE_NAME
          pip install -r requirements.txt
    - save_cache:
        paths:
          - ./venv
        key: v1-dependencies-{{ .Environment.MODULE_NAME }}-{{ checksum "requirements.txt" }}
    - run:
        name: Lint module
        command: |
          . venv/bin/activate
          pylint modules/pangea_modules/$MODULE_NAME

# CircleCI Jobs
jobs:
  lint_base:
    <<: *default_lint
    environment:
      MODULE_NAME: base

workflows:
  version: 2

  base_cd:
    jobs:
      - lint_base
